keys:
  - &yuxqiu age1mr92vpz2j6rplggpjm772lx2tsal7tja7pteyvkt5efvewc36atqlvm86r
  - &yuxqiu_laptop age1q9n0jkyt04747w62ydkwsm0cu0u9lxpm744j87azgsv9u70sgc0srm2h6r
creation_rules:
  - path_regex: profiles/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *yuxqiu
          - *yuxqiu_laptop
