code --install-extension albert.TabOut
code --install-extension antfu.icons-carbon
code --install-extension asvetliakov.vscode-neovim
code --install-extension bierner.emojisense
code --install-extension bierner.markdown-mermaid
code --install-extension codezombiech.gitignore
code --install-extension cschlosser.doxdocgen
code --install-extension EditorConfig.EditorConfig
code --install-extension James-Yu.latex-workshop
code --install-extension jeanp413.open-remote-ssh
code --install-extension llvm-vs-code-extensions.vscode-clangd
code --install-extension marp-team.marp-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.hexeditor
code --install-extension nvarner.typst-lsp
code --install-extension rangav.vscode-thunder-client
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension Remisa.shellman
code --install-extension rust-lang.rust-analyzer
code --install-extension twxs.cmake
code --install-extension usernamehw.errorlens
code --install-extension vadimcn.vscode-lldb
code --install-extension valentjn.vscode-ltex
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension Vue.volar
code --install-extension waderyan.gitblame
code --install-extension xaver.clang-format
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
