code --install-extension albert.tabout
code --install-extension antfu.icons-carbon
code --install-extension bierner.emojisense
code --install-extension bierner.markdown-mermaid
code --install-extension cschlosser.doxdocgen
code --install-extension dbankier.vscode-quick-select
code --install-extension drcika.apc-extension
code --install-extension editorconfig.editorconfig
code --install-extension foam.foam-vscode
code --install-extension james-yu.latex-workshop
code --install-extension llvm-vs-code-extensions.vscode-clangd
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension nmsmith89.incrementor
code --install-extension nvarner.typst-lsp
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension remisa.shellman
code --install-extension rust-lang.rust-analyzer
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tomoki1207.pdf
code --install-extension twxs.cmake
code --install-extension usernamehw.errorlens
code --install-extension usernamehw.find-jump
code --install-extension vadimcn.vscode-lldb
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vue.volar
code --install-extension waderyan.gitblame
code --install-extension xaver.clang-format
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
