codium --install-extension albert.TabOut
codium --install-extension antfu.icons-carbon
codium --install-extension antfu.smart-clicks
codium --install-extension asvetliakov.vscode-neovim
codium --install-extension bierner.emojisense
codium --install-extension bierner.markdown-mermaid
codium --install-extension codezombiech.gitignore
codium --install-extension cschlosser.doxdocgen
codium --install-extension EditorConfig.EditorConfig
codium --install-extension James-Yu.latex-workshop
codium --install-extension jeanp413.open-remote-ssh
codium --install-extension llvm-vs-code-extensions.vscode-clangd
codium --install-extension marp-team.marp-vscode
codium --install-extension ms-azuretools.vscode-docker
codium --install-extension ms-python.isort
codium --install-extension ms-python.python
codium --install-extension ms-python.vscode-pylance
codium --install-extension ms-toolsai.jupyter
codium --install-extension ms-vscode.cmake-tools
codium --install-extension ms-vscode.hexeditor
codium --install-extension nvarner.typst-lsp
codium --install-extension rangav.vscode-thunder-client
codium --install-extension redhat.java
codium --install-extension redhat.vscode-yaml
codium --install-extension Remisa.shellman
codium --install-extension rust-lang.rust-analyzer
codium --install-extension twxs.cmake
codium --install-extension usernamehw.errorlens
codium --install-extension vadimcn.vscode-lldb
codium --install-extension valentjn.vscode-ltex
codium --install-extension vscjava.vscode-java-debug
codium --install-extension vscjava.vscode-java-test
codium --install-extension vscjava.vscode-maven
codium --install-extension vscode-icons-team.vscode-icons
codium --install-extension Vue.volar
codium --install-extension waderyan.gitblame
codium --install-extension WakaTime.vscode-wakatime
codium --install-extension xaver.clang-format
codium --install-extension yzhang.markdown-all-in-one
codium --install-extension zhuangtongfa.material-theme
