#!/bin/sh
# from https://git.j3s.sh/dotfiles/blob/main/bin/getcert
# display certs from an https url

url="$1"
parsed_url=$(printf "%s" "$url" | sed 's|https://||g')
printf '\n' | openssl s_client -connect "$parsed_url":443 -showcerts | openssl x509 -noout -text

