#!/bin/zsh

source ~/.zshrc

set -e
set -u
set -o pipefail
set -x

pyact pwd
notify-send "Texify: started"
grim -g "$(slurp)" - | python ~/.config/sway/latex-ocr.py | wl-copy
notify-send "Texify: completed"
