# Content below (aside from this wrapper) was generated by
# `nixos-generate-config` via nixos-anywhere's --generate-hardware-config.
# Do not hand-edit the generated portion; may be overwritten by future runs.
{
  flake.modules.nixos.snowflake-dracaena =
    { lib, modulesPath, ... }:
    {
      imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "virtio_pci"
        "virtio_scsi"
        "usbhid"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ ];
      boot.extraModulePackages = [ ];

      nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
    };
}
